import React from "react";

const Blogs = [
  {
    id: 1,
    header: "My first Blog after University",
    author: "By Melissa Udoni | 09/02/21",
    body: "I just recently finished university, and now I have a degree, zero sleep, and a very strong opinion on instant noodles...",
    essay:
      "I just recently finished university, and now I have a degree, zero sleep, and a very strong opinion on instant noodles. This, I have learned, is the unofficial starter pack for post-university life. Graduation did not arrive with fireworks or a dramatic movie soundtrack. Instead, it showed up quietly, like a notification you accidentally swipe away, leaving you wondering what just happened and whether you were supposed to feel more prepared. University, in theory, is designed to educate you. In practice, it is a carefully structured experiment to see how long a human can survive on caffeine, deadlines, and false confidence. Over the years, I was taught many important things: how to reference properly, how to write 2,000 words on a topic I barely understood the night before submission, and how to convince myself that “I work best under pressure” was a personality trait and not a cry for help. These skills, I am told, are transferable. The degree itself is a fascinating object. It is a piece of paper that represents years of effort, stress, growth, and tuition fees. Society treats it like a golden key, but no one tells you what door it actually opens. Employers want experience. Universities gave us theory. Somewhere in between is a gap wide enough to swallow an entire graduating class. This is where instant noodles come in. Affordable, fast, and emotionally reliable, they become less of a meal and more of a lifestyle choice. From a nutritional standpoint, they are questionable. From a survival standpoint, they are undefeated. Now, standing on the other side of graduation, there is a strange mix of pride and confusion. Pride because finishing university is genuinely hard. Confusion because the structure that once dictated your life has vanished overnight. No timetable, no semester calendar, no clear next step. Just you, your degree, and a sudden responsibility to figure things out. This transition is not talked about enough, yet it is one of the most educational parts of the entire journey. In the end, university is less about becoming an expert in your field and more about becoming someone who can adapt, learn, and survive uncertainty. The degree is proof that you showed up, struggled, learned, failed, improved, and kept going. The instant noodles are proof that you did it realistically. And while I may still be tired, slightly confused, and deeply opinionated about food that comes in packets, I am also better equipped than I was before. If nothing else, university taught me that growth is uncomfortable, progress is messy, and sometimes success looks like graduating with a smile, a certificate, and a kettle permanently on standby.",
  },
  {
    id: 2,
    header: "My Blog at the beach",
    author: "By Damain Priest | 28/01/26",
    body: "I just came back from the beach and somehow managed to get sand in places I didn’t know existed...",
    essay:
      "I just came back from the beach and somehow managed to get sand in places I didn’t know existed. At this point, I’m convinced sand is not a physical substance but a lifestyle choice. It doesn’t just stick to you, it commits. You can shower for twenty minutes, exfoliate like your life depends on it, and still find evidence of the beach three business days later. The beach itself is a beautiful lie. From a distance, it looks peaceful, cinematic even. The waves sparkle, the breeze feels gentle, and everyone on social media appears relaxed and moisturised. In reality, the sun is aggressively personal, the wind exists purely to slap you with grains of sand, and the ocean seems determined to test your balance and dignity at the same time. There is nothing humbling quite like being knocked over by a wave while trying to look cool. Scientifically speaking, sand is fascinating. It is made of tiny rock and mineral fragments shaped by years of erosion. Emotionally speaking, it is nature’s glitter. Once it touches you, it becomes part of your identity. It follows you into your bag, your car, your bed, and possibly your future. I am fairly sure I brought half the beach home with me, and I would like to formally apologise to the coastline. Despite all this, there is something educational about a beach trip. You learn the limits of sunscreen, the importance of hydration, and the fact that seagulls have absolutely no respect for personal space. You also learn that food tastes better when eaten slightly sandy, because at that point, resistance is pointless. In the end, I would still go back. The beach may be uncomfortable, inconvenient, and mildly traumatic, but it is also oddly refreshing. It reminds you that nature does not care about your plans, your outfit, or your desire to stay clean. And honestly, after a long year, being humbled by sand feels strangely therapeutic.",
  },
  {
    id: 3,
    header: "Blog at UCL final",
    author: "By Ilori Boluwatife | 20/05/25",
    body: "As a Liverpool fan, I spent the whole match screaming and shouting, cheering on...",
    essay:
      "As a Liverpool fan, I spent the whole match screaming and shouting, cheering on my team as if my vocal cords were personally responsible for the final score. From kickoff, I was fully emotionally invested, which is a dangerous state to be in when your happiness depends on eleven men, a ball, and a referee who may or may not have functioning eyesight. Every pass felt like a statement, every missed chance like a personal betrayal. Watching a big match as a fan is less of a leisure activity and more of a full-body experience. My heart rate fluctuated wildly, my hands refused to stay still, and I developed an impressive collection of tactical opinions despite having no coaching qualifications whatsoever. According to my expert analysis, everything is either “brilliant football” or “an absolute disaster,” with no space in between. This is the scientific fan spectrum. There is also the psychological warfare involved. Superstition becomes law. You sit in the same position, wear the same shirt, and avoid moving during important moments because, obviously, the team’s performance is directly linked to whether you shift on the couch. Rational thinking leaves the room entirely. At this point, football is no longer a sport; it is a ritual. The educational value of supporting Liverpool during a tense match should not be underestimated. It teaches patience, resilience, and how to manage extreme emotions in a short period of time. It also teaches you humility, especially when you celebrate too early and immediately regret it. These lessons are delivered quickly and without mercy. When the final whistle finally blew, I was exhausted. Win or lose, supporting Liverpool demands energy, commitment, and a willingness to suffer slightly for the sake of passion. Yet, despite the stress, the shouting, and the emotional rollercoaster, I would do it all again. Because being a Liverpool fan isn’t just about football. It’s about loyalty, hope, and believing, against all logic, that next time will be even better.",
  },
  {
    id: 4,
    header: "Taking my dog on a walk",
    author: "By Rijkaard Lee | 31/11/22",
    body: "It might be cold, but my dog doesn’t care—he’s dragging me out the door like I owe him money. Honestly, I think he enjoys...",
    essay:
      "It might be cold, but my dog doesn’t care—he’s dragging me out the door like I owe him money. Honestly, I think he enjoys the whole process, from the brisk tug on the leash to my dramatic protests, and the look of mild panic on my face as I fumble for my scarf. Dogs have this remarkable ability to find joy in things humans consider torture, like early-morning walks in freezing weather, puddles, mud, and that one patch of grass that is suspiciously wet. Meanwhile, I am functioning at approximately twenty percent human capacity, questioning my life choices and wondering if I can blame the weather for everything. Walking a dog is less a simple exercise routine and more a negotiation with a small, four-legged dictator who has perfected the art of persuasion. He sets the pace, chooses the route, and somehow knows when to stop for maximum dramatic effect. Every tree becomes a point of interest, every passerby a subject of intense scrutiny, and every squirrel a personal affront to his canine dignity. You learn quickly that resistance is futile; dogs operate on a scale of enthusiasm that human logic cannot comprehend. In this case, my resistance merely fuels his determination, and his excitement is contagious, whether I like it or not. There’s an unexpected lesson in these walks, though. You see the world differently when someone—or something—is dragging you along. Ordinary streets become adventures, mundane corners become exploration zones, and cold air becomes refreshing rather than biting. My dog’s enthusiasm forces me to be present in the moment, noticing things I would otherwise ignore: the way the sunlight glints off frost, the sound of leaves crunching underfoot, or the smell of coffee from the café we pass. It’s an immersive experience, and he’s the unwilling, yet willing, tour guide. Of course, there’s also the humor of the situation. There’s something deeply funny about being outpaced by a creature who is half your size, who looks at you with that smug little face as if to say, “This is why you don’t have my stamina.” You end up laughing at yourself, at the absurdity of being controlled by a dog, and at the pure, unfiltered joy that your companion exudes in the cold. By the end of the walk, I am tired, chilled, and questioning my choices in outerwear, but I am also strangely grateful. My dog’s insistence on exploring the world, rain or shine, cold or not, reminds me to embrace life with curiosity, persistence, and a little bit of madness. He teaches me that joy is often found not in comfort but in action, and sometimes the best experiences are the ones you’re dragged into, whether you’re ready or not. And so, despite the cold, the tugging, and my initial complaints, I step outside willingly, because with him leading the way, life becomes an adventure I wouldn’t miss for the world.",
  },
];

export default Blogs;
